# Generated by Django 2.2 on 2020-03-04 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200304_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 3, 4, 10, 3, 43, 820167, tzinfo=utc), max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
