# Generated by Django 2.2 on 2020-03-04 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketingpreference_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='key',
            field=models.CharField(default=datetime.datetime(2020, 3, 4, 10, 56, 20, 803236, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
