# Generated by Django 2.2 on 2020-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_marketingpreference_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
