# Generated by Django 2.2 on 2020-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200325_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
