# Generated by Django 2.2 on 2020-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
