# Generated by Django 2.2 on 2020-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='popular',
            new_name='is_popular',
        ),
        migrations.AddField(
            model_name='course',
            name='num_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
