# Generated by Django 2.2 on 2020-02-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
