# Generated by Django 2.2 on 2020-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200516_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
