# Generated by Django 2.2 on 2020-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='start_letter',
            field=models.CharField(blank=True, max_length=1, null=True, unique=True),
        ),
    ]
