# Generated by Django 2.2 on 2020-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200320_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='provider',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
