# Generated by Django 2.2 on 2020-05-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_num_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['num_subscribers']},
        ),
    ]
