# Generated by Django 2.2 on 2020-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subcategory_start_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='start_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
