# Generated by Django 2.2 on 2020-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200215_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='start_letter',
        ),
        migrations.AddField(
            model_name='provider',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
