# Generated by Django 2.2 on 2020-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
