# Generated by Django 2.2 on 2020-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='plan_details',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
