# Generated by Django 2.2 on 2020-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
