# Generated by Django 2.2 on 2020-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_provider_plan_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
