# Generated by Django 2.2 on 2020-04-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200404_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='courses.SubCategory'),
        ),
    ]
