# Generated by Django 2.2 on 2020-05-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200509_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='certificate',
            new_name='has_certificate',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Category')),
                ('subcategory', models.ManyToManyField(blank=True, to='courses.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ManyToManyField(blank=True, to='courses.Topic'),
        ),
    ]
